language: java
before_script: cd swingbits
#script: mvn deploy --settings deploy-settings.xml
script: mvn test -B
jdk:
- oraclejdk8
dist: trusty
#env:
#  global:
#  - secure: YxhQo3hQnG3cXcXioSl2u3HGlzfmUTuB1jJCSL6E4+c+yN2MAhUfeXWrmVRpFbkvwtCfXugfVOrpjnvR9z58ASTa2H7jzxqw2Cl6lEKww/++SGgpTrn/ygDuPiAYJTH+GEm4AQCAEy226qctrXdlS675uCCHw/Zd3082tJI1iu8=
#  - secure: WxMbcit/FwjP/xtJUCZtlDSD2HM2YcU7ZVjJDnAvCPi4Sv8lVcj/ZbPU5wvQbQAPAnpberdSNXoaMeMqDCkHdXkrDjIdU6ogAOiTiGj8IT1MmOAjQInCEcDmTfZljPrAOHitmhV7a9Dz8sd8bA//A8oDIGBcgFOAnigpiGL8aEw=
